version: '3.1'

services:
  mongodb:
    image: mongo:${MONGO_IMAGE_VERSION}
    container_name: mongo
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:?err}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:?err}